### ISSUE TITLE
[EC2] too binding detection

### ISSUE THREAD

**Issue by TristanL06** [green-code-initiative/ecoCode#346] opened 2024-07-22 08:44 UTC
**Describe the bug**
The EC2 rule detect multiple if-else and ask to replace them by a single switch-case. This rule should detect only more than 4 variable access if-else since #222 and issue #216 but still detecting 2-variable-access code.

**To Reproduce**
on code :
```java
if (a == null || b == null) {
    if (a == null) {
        ...
    } else {
        ...
    }
}
```
This code should be compliant but it is rased as non compliant for rule EC2.

**Software Versions**
 - SonarQube Version: comunity 10.5.1
 - Plugin Version: 1.6.1

**Comment by dedece35** [comment] 2024-07-22 20:24
Hi @TristanL06,
thank you for the issue.
As seen together, here is an exaplanation : 
- in your example code, a is use 3 times (2 explicit uses and 1 implicit use with "else")
- in ecoCode-java plugin, if a variable is used more than 2, the issue will be raised. This is why the issue is raised
- if you want another way to write your code : return quickly as possible : 
```
if (a != null && b != null) {
   return;
}

if (a == null) {
     ...
} else {
     ...
}
...
```

**Comment by dedece35** [comment] 2024-07-22 20:24
if we are ok, I will close this issue.
ok for you @TristanL06  ?

**Comment by TristanL06** [comment] 2024-07-22 20:51
it seems clear for me

**Closed** 2024-07-22 21:37 UTC
Labels: :card_file_box: rule, 🔥 in progress 🔥, 👀 👀 waiting commiter 👀 👀
